meta_product_name: "RemoteKick"
meta_title: "RemoteKick - Remote working. On caffeine."
meta_description: "Get to work, minus the office."
meta_image: "logo_250w.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
