meta_product_name: "wifiWarriors"
meta_title: "WifiWarriors - Remote working. On caffeine."
meta_description: "Get to work, minus the office."
meta_image: "wifiwarriors_logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
